### ISSUE TITLE
 Cannot compile test suite in LTS 8.x

### ISSUE THREAD

**Issue by peti** [haskell-hvr/uuid#28]
LTS 8.x has HUnit 1.5, but this package requires HUnit >=1.2 && <1.4. Would it be possible to extend support for later versions of HUnit?

**Comment by clinty** [comment]
This problem affects both uuid and uuid-types.

**Comment by hvr** [comment]
This will be addressed in the next release (or in the next .cabal revision, if it becomes necessary for the library components to perform a revision). There's likely going to be a new release next week or the one after it.

**Comment by clinty** [comment]
HUnit 1.6 is now relevant.

**Comment by clinty** [comment]
Also QuickCheck 2.12.6.1
