### ISSUE TITLE
Support building against entropy-0.4.*

### ISSUE THREAD

**Issue by DanBurton** [haskell-hvr/uuid#34]
The `uuid` package is currently constrained to `entropy < 0.4`.

**Comment by hvr** [comment]
Thanks for the reminder; I'll look into this tomorrow

**Comment by juhp** [comment]
@23Skidoo's PR LGTM - can it be merged?

**Comment by hvr** [comment]
This was already resolved last week via [`uuid-1.3.13-r2`](http://hackage.haskell.org/package/uuid-1.3.13/revisions/). Unfortunately, this took me a bit longer than expected to perform the due diligence needed to allow the use the new major version of `entropy`; and in the mean time people could simply use `--allow-newer=uuid-1.3.13:entropy` (which can be easily added to your `cabal.project` config as well) to workaround this issue locally.
