### ISSUE TITLE
GHCJS no longer supported

### ISSUE THREAD

**Issue by alexanderkjeldaas** [haskell-hvr/uuid#37]
The entropy dependency should be removed so this builds on GHCJS.

**Comment by hvr** [comment]
What facilities are available in GHCJS to provide a good quality entropy source?

**Comment by alexanderkjeldaas** [comment]
The crypto API provides good entropy sources https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues  [widely supported](https://caniuse.com/#feat=getrandomvalues)
If not, there's `Math.random()` as fallback AFAIK.

**Comment by hvr** [comment]
Thanks to @eskimor's efforts the latest `entropy` release contains https://github.com/TomMD/entropy/pull/47 so I consider this issue here transitively addressed via `entropy-0.4.1.5`.
