### ISSUE TITLE
Loosen dependency on binary?

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-hvr/uuid#43]
Does uuid need its dependency of binary loosened?  The current dependency is `< 0.9` but binary `0.10.0.0` is out: https://hackage.haskell.org/package/binary-0.10.0.0

**Comment by hvr** [comment]
no, it does not need its dependency loosened because `binary-0.9` and `binary-0.10` were accidental releases which are marked deprecated; as such they don't exist nor do they need to be taken into account.

**Comment by tomjaguarpaw** [comment]
Thanks, I could not tell that they were deprecated.  I have reported [this UI issue on the hackage-server package](https://github.com/haskell/hackage-server/issues/794).
