### ISSUE TITLE
Hackage Release

### ISSUE THREAD

**Issue by andrewthad** [haskell-hvr/uuid#46]
The `uuid-types` library has seen some pretty important performance improvements in the last three years, but none of these have been released to hackage. It would be nice to see a new release.

**Comment by hvr** [comment]
I know; it's partly because I ran into some minor regressions while benchmarking which left me worrying; I need to pick it up again and revisit the measurements; and also complete some minor other tweaks I got distracted from completing in the API.

**Comment by andrewthad** [comment]
Is there anything I can do to help with this? Do you recall what had regressed?

**Comment by phadej** [comment]
https://hackage.haskell.org/package/uuid-types-1.0.4
