### ISSUE TITLE
A way of not requiring `network-info`?

### ISSUE THREAD

**Issue by danwdart** [haskell-hvr/uuid#64]
Looks like the latest versions require `network-info`, but it would be great to not have to use it for the purposes of using on wasm targets.

**Comment by phadej** [comment]
Why you need `uuid` (and not just `uuid-types`)?

**Comment by danwdart** [comment]
Suppose I could pull out `nextRandom` from V4, with just `entropy`... all I'm after is to create secure UUIDv4s, then again I could still just use the insecure `Random` instance.

**Comment by danwdart** [comment]
That'll do, thanks for the suggestion.

**Comment by phadej** [comment]
Yes, there was an idea to make `uuid-types` depend on `entropy`. As `Random` instance there is ~useless, and it would be better to rather provide proper random generation.

Never got to it, as it is a breaking change and I hadn't any push to do it. Would that solve your need better, i.e. so you wouldn't need to copy code?

**Comment by danwdart** [comment]
I don't currently require cryptographically secure, only semi- (reasonably) random UUIDs, so the `random` instance should be enough for me for now.

**Comment by dhess** [comment]
We're now planning to switch to `uuid-types` for the same reason (Wasm). While we don't *need* cryptographically secure randomness in `uuid-types`, I'd feel less uneasy about the switch if `uuid-types` did support it.

**Comment by phadej** [comment]
Does wasm backend support `entropy` package?

**Comment by dhess** [comment]
No, at least not on `9.6.3` :( Just discovered that myself:

```
Installing   optics-th-0.4.1 (lib)
Completed    optics-th-0.4.1 (lib)
Installing   unordered-containers-0.2.19.1 (lib)
Completed    unordered-containers-0.2.19.1 (lib)
Error: cabal: Failed to build entropy-0.4.1.10 (which is required by
primer-0.7.2.0). The failure occurred during the configure step. The exception
was:
/home/dhess/.ghc-wasm/.cabal/logs/ghc-9.6.3.20230927/entropy-0.4.1.10-b65ded69d211e802c4307752c6b8782dd27765865f8d702c1ae24e9fce6e15a0.log:
withFile: user error (Error: cabal:
'/nix/store/z8hizfp51krrfccb0pfqvr8wyvdp6kwv-wasm32-wasi-ghc-9.6/bin/wasm32-wasi-ghc'
exited with an error:
wasm-ld: error: unable to find library -lHSrts-1.0.2_thr
clang: error: linker command failed with exit code 1 (use -v to see
invocation)
wasm32-wasi-ghc-9.6.3.20230927: `clang' failed in phase `Linker'. (Exit code:
1)
)
```
