### ISSUE TITLE
Support GHC-9.6

### ISSUE THREAD

**Issue by ysangkok** [haskell-hvr/uuid#74]
Compiling yields:

```
[__1] trying: uuid-1.3.15 (dependency of amazonka)
[__2] trying: uuid-types-1.0.5 (dependency of uuid)
[__3] next goal: template-haskell (dependency of uuid-types)
[__3] rejecting: template-haskell-2.20.0.0/installed-2.20.0.0 (conflict:
uuid-types => template-haskell>=2.7.0.0 && <2.20)
``` 

Allow-newer seems to work, so a revision would be sufficient.

**Comment by phadej** [comment]
uuid-types is done in https://github.com/haskell-hvr/uuid/pull/75

The `uuid` will take some time, but it will resolve by itself when dependencies catch up
