### ISSUE TITLE
Support GHC 9.10

### ISSUE THREAD

**Issue by ulysses4ever** [haskell-hvr/uuid#82]

**Comment by phadej** [comment]
Blocked on https://github.com/haskell/entropy/issues/84

**Comment by ysangkok** [comment]
Looks like uuid-types-1.0.6 was uploaded on May 16th, and it is compatible with template-haskell-2.22. But since [uuid](https://hackage.haskell.org/package/uuid)-1.3.15 isn't compatible with it yet, I suppose this is still blocked on entropy.

**Comment by tomjaguarpaw** [comment]
Is it still blocked on entropy? If so, in what way? This works, for example:

```
cabal repl -z -b uuid -w ghc-9.10 '--allow-newer=uuid:uuid-types'
```

**Comment by phadej** [comment]
> Is it still blocked on entropy? If so, in what way?

Yes. `entropy` is not buildable with `Cabal-3.12` bundled with GHC-9.10. If you allow downgrade, it will, but I don't (nor will Stackage when it gets to it).

**Comment by tomjaguarpaw** [comment]
Could you elaborate on how exactly the non-buildability manifests? This works fine, for example:

```
cabal -z repl -b entropy -b 'Cabal>=3.12' -w ghc-9.10
```

**Comment by phadej** [comment]
Use `-c 'any.Cabal ^>=3.12'` to restrict also setup (and `build-tool-depends`) dependencies.

**Comment by tomjaguarpaw** [comment]
Oh, it's one of those `Setup.hs` things?

**Comment by andreasabel** [comment]
> Blocked on [haskell/entropy#84](https://github.com/haskell/entropy/issues/84)

This is resolved.

**Comment by phadej** [comment]
@andreasabel thanks for the ping, i'll take a look now
